# Generated by Django 5.2.2 on 2025-06-08 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Padaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('padaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.padaria')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('padaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.padaria')),
            ],
            options={
                'unique_together': {('usuario', 'padaria')},
            },
        ),
    ]
